[phases.setup]
aptPkgs = [
    "libgobject-2.0-0", 
    "libpango-1.0-0", 
    "libpangoft2-1.0-0", 
    "libgdk-pixbuf2.0-0", 
    "libffi-dev", 
    "shared-mime-info"
]

[phases.build]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "python launcher_prod.py"
