# 🚂 Railway Deploy Configuration - REDEPLOY FORÇADO

# Especifica a versão do Python
[build]
python = "3.12"

# Comando para iniciar o aplicativo
[deploy]
start = "python3 dashboard_only.py"

# Variáveis de ambiente necessárias
[env]
PYTHONUNBUFFERED = "1"
PYTHONDONTWRITEBYTECODE = "1"
