# Arquivo central para definir todos os estados de conversa
# Isso evita importações circulares e conflitos de ranges.

# =============================================================================
# ESTADOS ORGANIZADOS POR FUNCIONALIDADE (RANGES ÚNICOS)
# =============================================================================

# --- GERENTE FINANCEIRO (1-10) ---
(AWAIT_GERENTE_QUESTION,) = range(1, 2)

# --- ONBOARDING (11-20) ---
(ASK_NAME,) = range(11, 12)
(
    ADD_CARTAO_NOME, ADD_CARTAO_FECHAMENTO, ADD_CARTAO_VENCIMENTO, ADD_CARTAO_LIMITE,
    ASK_ADD_ANOTHER_CARTAO, ADD_CONTA_NOME, ASK_ADD_ANOTHER_CONTA, ASK_HORARIO, COMPLETE
) = range(13, 22)

# --- LANÇAMENTO MANUAL E OCR (80-99) ---
(
    AWAITING_LAUNCH_ACTION,
    ASK_DESCRIPTION, ASK_VALUE, ASK_CONTA,
    ASK_CATEGORY, ASK_SUBCATEGORY, ASK_DATA,
    OCR_CONFIRMATION_STATE
) = range(80, 88)

# --- OBJETIVOS/METAS (100-119) ---
(ASK_OBJETIVO_DESCRICAO, ASK_OBJETIVO_VALOR, ASK_OBJETIVO_PRAZO) = range(100, 103)
(ASK_EDIT_VALOR, ASK_EDIT_PRAZO) = range(110, 112)

# --- AGENDAMENTOS (200-219) ---
(
    ASK_TIPO, ASK_DESCRICAO_AGENDAMENTO, ASK_VALOR_AGENDAMENTO, ASK_CATEGORIA_AGENDAMENTO, 
    ASK_PRIMEIRO_EVENTO, ASK_FREQUENCIA, ASK_TIPO_RECORRENCIA, ASK_TOTAL_PARCELAS, 
    CONFIRM_AGENDAMENTO
) = range(200, 209)

# --- CADASTRO DE CARTÃO REMOVIDO - FUNCIONALIDADE TRANSFERIDA PARA ONBOARDING_HANDLER.PY ---

# --- CADASTRO DE EMAIL (320-329) ---
(AWAIT_EMAIL_NOTIFICACAO,) = range(320, 321)

# --- ONBOARDING CONFIGURAR (400-429) ---
(
    MENU_PRINCIPAL, ADD_CONTA_NOME, ASK_ADD_ANOTHER_CONTA,
    ADD_CARTAO_NOME, ADD_CARTAO_FECHAMENTO, ADD_CARTAO_VENCIMENTO, ADD_CARTAO_LIMITE, ASK_ADD_ANOTHER_CARTAO,
    ASK_HORARIO, PERFIL_ASK_RISCO, PERFIL_ASK_OBJETIVO, PERFIL_ASK_HABITO,
    GERENCIAR_CONTAS, GERENCIAR_CARTOES
) = range(400, 414)

# --- EDITING HANDLER (500-519) ---
(
    CHOOSE_METHOD, AWAIT_SEARCH_QUERY, CHOOSE_LANCAMENTO,
    CHOOSE_FIELD_TO_EDIT, AWAIT_NEW_VALUE, AWAIT_NEW_CATEGORY, AWAIT_NEW_SUBCATEGORY
) = range(500, 507)

# --- DELETE USER (600-609) ---
(CONFIRM_DELETION,) = range(600, 601)

# --- CONTACT HANDLER (700-719) ---
(MENU_CONTATO, AWAIT_SUBJECT, AWAIT_BODY) = range(700, 703)