# docker-compose.yml
version: '3.8'

services:
  # Backend
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/maestro_db
      - SECRET_KEY=sua-chave-secreta-aqui
    depends_on:
      - db
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  # Frontend
  frontend:
    build: ./maestrofin-web
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    volumes:
      - ./maestrofin-web:/app
    command: npm run dev

  # Banco PostgreSQL
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=maestro_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
